version: "3"
services:
  lsi_db:
    image: postgres:14.1-alpine
    container_name: lsi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - .dbdata:/var/lib/postgresql/data
  lsi_backend:
    container_name: lsi_backend
    build: .
    command: [ "air" ]
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - lsi_db